apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jetson-exporter
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      port: http
      relabelings:
        - action: replace
          regex: (.*);.*:(.*)
          replacement: $1:$2
          sourceLabels:
            - __meta_kubernetes_pod_node_name
            - __address__
          targetLabel: __address__
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
      scheme: http
  jobLabel: app
  selector:
    matchLabels:
      app: jetson-exporter
